### ISSUE TITLE
References to classes in external packages are dropped in document

### ISSUE THREAD

**Issue by scottmcclung** [SCWells72/IcApexDoc#8]
When referencing a class in a package outside of the repo, the reference is excluded from the resulting documentation.  
Example: for this `Accounts` class the parent `fflib_SObjects` class lives in an unlocked package outside of the main repo.
```
public inherited sharing class Accounts extends fflib_SObjects implements IAccounts {}
```

The class signature in the resulting documentation does not reflect the parent class and also drops the reference to the interface.  The interface does exist in the local repo.

<img width="502" alt="example" src="https://user-images.githubusercontent.com/328460/226489510-0e526266-80c5-4cf8-aa4e-4e4a2756b62b.png">

Would be ideal if the class signature was reflected correctly even if the parent class itself is not found.  Similar to the way the method signatures behave.
![image](https://user-images.githubusercontent.com/328460/226490959-80001c0a-9b37-47db-863f-a6fc43da8925.png)

**Comment by SCWells72** [comment]
Thanks for logging, Scott. This seems to be due to a behavior of the Salesforce Apex jorje compiler. I saw the same thing with the stanadard lib types until I added them to the actual compilation. IcApexDoc consumes the output of that compilation. I think the only solution is likely to include those in the same compilation run, but I've already pinged a few key folks at Salesforce to see what options are available. I'll post anything I learn here, and of course if there are good options for incorporating "outside" types better, I'll certainly plan to apply them.

**Comment by SCWells72** [comment]
FYI, I've figured out a way to address this by having IcApexDoc include org-resident Apex types in its compilation pass. Once the new release is available (hopefully later this week), you'll need to run it with the new `-u/--username <usernameOrAlias>` argument so that it can query the org for the names and bodies of org-resident Apex types. By default those types are **not** included in the generated ApexDoc--though relationships to them are--but if you want them to be included, you can use the new `-i/--include-org-types` argument as well.

**Comment by SCWells72** [comment]
Delivered in [1.0.0.2](https://github.com/SCWells72/IcApexDoc/releases/tag/1.0.0.2).
